apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: application-database
  namespace: "application-dev"
  labels:
    verion: "8.0.31"
    type: "sql"
    purpose: "application-data"
spec:
  replicas: 2
  selector:
    matchLabels:
      version: "8.0.31"
      type: "sql"
      purpose: "application-data"
  serviceName: "mysql-app-data-svc"
  template:
    metadata:
      labels:
        version: "8.0.31"
        type: "sql"
        purpose: "application-data"
    spec:
      hostname: "app-data-db-mysql"
      containers:
        - name: "app-data-db-mysql"
          image: "mysql:8.0.31"
          imagePullPolicy: IfNotPresent
          ports:
            - name: "app-data-db-mysql-port"
              containerPort: 3306
              protocol: "TCP"
          envFrom:
            - 