apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: frontend-admin
    stage: 
  name: frontend-admin
  namespace: 
spec:
  replicas: 1
  selector:
    matchLabels:
      application: frontend-admin
      stage: 
  template:
    metadata:
      labels:
        application: frontend-admin
        stage: 
    spec:
      containers:
      - env:
        - name: REACT_APP_BASE_URL
          valueFrom:
            configMapKeyRef:
              key: API_URL
              name: backend-app-cm
        image: qrsmartmenu/frontend-admin:0.1.0-rc1
        imagePullPolicy: IfNotPresent
        name: frontend-admin
        ports:
        - containerPort: 3000
          name: front-adm-port
          protocol: TCP
      restartPolicy: Always
