apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: frontend-restaurant
    stage: 
  name: frontend-restaurant
  namespace: 
spec:
  replicas: 1
  selector:
    matchLabels:
      application: frontend-restaurant
      stage: 
  template:
    metadata:
      labels:
        application: frontend-restaurant
        stage: 
    spec:
      containers:
      - env:
        - name: REACT_APP_BASE_URL
          valueFrom:
            configMapKeyRef:
              key: API_URL
              name: backend-app-cm
        image: qrsmartmenu/frontend:0.1.0
        imagePullPolicy: IfNotPresent
        name: frontend-restaurant
        ports:
        - containerPort: 3000
          name: front-rest-port
          protocol: TCP
      restartPolicy: Always
