apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: "qr-backend-dev"
  namespace: "application-dev"
  labels:
    application: "backend"
    stage: "dev"
spec:
  replicas: 1
  strategy:
    blueGreen:
      autoPromotionEnabled: true
      autoPromotionSeconds: 180
      maxUnavailable: 1
      activeService: "backend-dev-svc"
      scaleDownDelaySeconds: 10
  selector:
    matchLabels:
      application: "backend"
      stage: "dev"
  template:
    metadata:
      labels:
        application: "backend"
        stage: "dev"
    spec:
      restartPolicy: Always
      containers:
        - name: backend-dev
          image: qrsmartmenu/backend:0.1.0-rc28
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: "backend-port"
              containerPort: 3000
              protocol: "TCP"
          env:
            - name: "DATABASE_HOST"
              valueFrom:
                configMapKeyRef:
                  key: "DATABASE_HOST"
                  name: "db-dev-cm"
            - name: "DATABASE_PORT"
              valueFrom:
                configMapKeyRef:
                  key: "DATABASE_PORT"
                  name: "db-dev-cm"
            - name: "DATABASE_NAME"
              valueFrom:
                configMapKeyRef:
                  key: "DATABASE_NAME"
                  name: "db-dev-cm"
            - name: "APP_URL"
              valueFrom:
                configMapKeyRef:
                  key: "APP_URL"
                  name: "frontend-app-dev-cm"
            - name: "API_URL"
              valueFrom:
                configMapKeyRef:
                  key: "API_URL"
                  name: "backend-app-dev-cm"
            - name: "APP_ENV"
              valueFrom:
                configMapKeyRef:
                  key: "APP_ENV"
                  name: "backend-app-dev-cm"
