apiVersion: apps/v1
kind: Deployment
metadata:
  name: "qr-backend-dev"
  namespace: "application-dev"
  labels:
    application: "backend"
    stage: "dev"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: "25%"
      maxUnavailable: "25%"
  selector:
    matchLabels:
      application: "backend"
      stage: "dev"
  template:
    metadata:
      labels:
        application: "backend"
        stage: "dev"
    spec:
      restartPolicy: Always
      containers:
        - name: backend-dev
          image: qrsmartmenu/backend:0.1.0-rc1
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: "backend-port"
              containerPort: 3000
              protocol: "TCP"
          env:
            - name: "MAIL_MAILER"
              valueFrom:
                secretKeyRef:
                  key: "MAIL_MAILER"
                  name: "app-mailer-secrets-dev"
            - name: "MAIL_HOST"
              valueFrom:
                secretKeyRef:
                  key: "MAIL_HOST"
                  name: "app-mailer-secrets-dev"
            - name: "MAIL_PORT"
              valueFrom:
                secretKeyRef:
                  key: "MAIL_PORT"
                  name: "app-mailer-secrets-dev"
            - name: "MAIL_USERNAME"
              valueFrom:
                secretKeyRef:
                  key: "MAIL_USERNAME"
                  name: "app-mailer-secrets-dev"
            - name: "MAIL_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: "MAIL_PASSWORD"
                  name: "app-mailer-secrets-dev"
            - name: "MAIL_FROM_ADDRESS"
              valueFrom:
                secretKeyRef:
                  key: "MAIL_FROM_ADDRESS"
                  name: "app-mailer-secrets-dev"
            - name: "DATABASE_HOST"
              valueFrom:
                configMapKeyRef:
                  key: "DATABASE_HOST"
                  name: "db-dev-cm"
            - name: "DATABASE_PORT"
              valueFrom:
                configMapKeyRef:
                  key: "DATABASE_PORT"
                  name: "db-dev-cm"
            - name: "DATABASE_USER"
              valueFrom:
                secretKeyRef:
                  key: "DATABASE_USER"
                  name: "db-dev-secrets"
            - name: "DATABASE_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: "DATABASE_PASSWORD"
                  name: "db-dev-secrets"
            - name: "DATABASE_NAME"
              valueFrom:
                configMapKeyRef:
                  key: "DATABASE_NAME"
                  name: "db-dev-cm"
            - name: "ADMIN_USERNAME"
              valueFrom:
                secretKeyRef:
                  key: "ADMIN_USERNAME"
                  name: "admin-secrets-dev"
            - name: "ADMIN_EMAIL"
              valueFrom:
                secretKeyRef:
                  key: "ADMIN_EMAIL"
                  name: "admin-secrets-dev"
            - name: "ADMIN_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: "ADMIN_PASSWORD"
                  name: "admin-secrets-dev"
            - name: "JWT_USER_SECRET_KEY"
              valueFrom:
                secretKeyRef:
                  key: "JWT_USER_SECRET_KEY"
                  name: "jwt-secrets-dev"
            - name: "JWT_ADMIN_SECRET_KEY"
              valueFrom:
                secretKeyRef:
                  key: "JWT_ADMIN_SECRET_KEY"
                  name: "jwt-secrets-dev"
            - name: "JWT_USER_EXPIRE_TIME"
              valueFrom:
                secretKeyRef:
                  key: "JWT_USER_EXPIRE_TIME"
                  name: "jwt-secrets-dev"
            - name: "JWT_ADMIN_EXPIRE_TIME"
              valueFrom:
                secretKeyRef:
                  key: "JWT_ADMIN_EXPIRE_TIME"
                  name: "jwt-secrets-dev"
            - name: "APP_URL"
              valueFrom:
                configMapKeyRef:
                  key: "APP_URL_INNER"
                  name: "frontend-app-dev-cm"
            - name: "API_URL"
              valueFrom:
                configMapKeyRef:
                  key: "API_URL"
                  name: "backend-app-dev-cm"
            - name: "APP_ENV"
              valueFrom:
                configMapKeyRef:
                  key: "APP_ENV"
                  name: "backend-app-dev-cm"
