apiVersion: v1
kind: Secret
metadata:
  name: "admin-secrets-dev"
  namespace: "application-dev"
  labels:
    stage: "dev"
    purpose: "admin"
data:
  ADMIN_USERNAME: "YWRtaW4="
  ADMIN_EMAIL: "YWRtaW5AZ21haWwuY29t"
  ADMIN_PASSWORD: "cXdlcnR5"
type: Opaque  
