apiVersion: v1
kind: Service
metadata:
  name: "backend-dev-svc-out"
  namespace: "application-dev"
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: "backend-port"
      protocol: "TCP"
  selector:
    application: "backend"
    stage: "dev"
