apiVersion: v1
kind: Service
metadata:
  name: app-db-svc
  namespace: 
spec:
  clusterIP: None
  ports:
    - port: 3306
      targetPort: app-db-port
      protocol: TCP
  selector:
    application: database
    stage: 