apiVersion: v1
kind: Service
metadata:
  name: db-client-svc
  namespace:
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: db-client-port
      protocol: TCP
  selector:
    application: db-client
    stage: 