apiVersion: v1
kind: Service
metadata:
  name: frontend-admin-svc
  namespace: 
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: front-adm-port
      protocol: TCP
  selector:
    application: frontend-admin
    stage:
