apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    application: frontend
    stage: dev
  name: qr-frontend-client-dev
  namespace: application-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      application: frontend-client
      stage: dev
  strategy:
    blueGreen:
      activeService: frontend-client-dev-svc
      autoPromotionEnabled: true
      autoPromotionSeconds: 30
      maxUnavailable: 1
      scaleDownDelaySeconds: 10
  template:
    metadata:
      labels:
        application: frontend-client
        stage: dev
    spec:
      containers:
      - env:
        - name: REACT_APP_BASE_URL
          valueFrom:
            configMapKeyRef:
              key: API_URL
              name: backend-app-dev-cm
        image: qrsmartmenu/frontend-client:0.1.0-rc4
        imagePullPolicy: IfNotPresent
        name: frontend-dev
        ports:
        - containerPort: 3000
          name: front-cli-port
          protocol: TCP
      restartPolicy: Always
