apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: "qr-frontend-dev"
  namespace: "application-dev"
  labels:
    application: "frontend"
    stage: "dev"
spec:
  replicas: 2
  strategy:
    blueGreen:
      autoPromotionEnabled: true
      autoPromotionSeconds: 30
      maxUnavailable: 1
      activeService: "frontend-dev-svc"
      scaleDownDelaySeconds: 10
  selector:
    matchLabels:
      application: "frontend"
      stage: "dev"
  template:
    metadata:
      labels:
        application: "frontend"
        stage: "dev"
    spec:
      restartPolicy: Always
      containers:
        - name: frontend-dev
          image: qrsmartmenu/frontend:0.1.0-rc14
          imagePullPolicy: IfNotPresent
          ports:
            - name: frontend-port
              containerPort: 3000
              protocol: "TCP"
          env:
            - name: REACT_APP_BASE_URL
              valueFrom:
                configMapKeyRef:
                  key: "API_URL"
                  name: "backend-app-dev-cm"
