apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-client
  namespace: application-dev
  labels:
    app: db-client
spec:
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer
          imagePullPolicy: IfNotPresent
          ports:
            - name: db-client-port
              containerPort: 8080
              protocol: "TCP"
          env:
            - name: ADMINER_DESIGN
              value: "pepa-linha-dark"
          readinessProbe:
            httpGet:
              path: "/"
              port: 8080
            successThreshold: 1
            failureThreshold: 1
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: "/"
              port: 8080
            successThreshold: 1
            failureThreshold: 1
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 5