apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-client
  namespace: application-dev
  labels:
    app: db-client
spec:
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer
          imagePullPolicy: IfNotPresent
          ports:
            - name: db-client-port
              containerPort: 8080
              protocol: "TCP"
          env:
            - name: ADMINER_DESIGN
              value: "pepa-linha-dark"