apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-client
  namespace:
  labels:
    application: db-client
    stage:
spec:
  selector:
    matchLabels:
      application: db-client
      stage:
  template:
    metadata:
      labels:
        application: db-client
        stage:
    spec:
      containers:
        - name: db-client
          image: phpmyadmin
          imagePullPolicy: IfNotPresent
          ports:
            - name: db-client-port
              containerPort: 80
              protocol: TCP
          env:
            - name: PMA_HOST
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_HOST
                  name: db-configs
            - name: PMA_PORT
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_PORT
                  name: db-configs
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 0
            failureThreshold: 1
            successThreshold: 1
            timeoutSeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 0
            failureThreshold: 1
            successThreshold: 1
            timeoutSeconds: 5
            periodSeconds: 5
