apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  namespace: 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 6Gi