resources:
  - ../../base

namespace: dev

commonLabels:
  stage: dev

configMapGenerator:
  - name: db-cm
    namespace: dev
    literals:
    - DATABASE_HOST=app-db-svc.dev.svc.cluster.local
    - DATABASE_PORT=3306
    - DATABASE_NAME=qr_menu

replicas:
  - name: database
    count: 1